apiVersion: v1
kind: Service
metadata:
    name: topnavapplication
    labels:
        app: topnavapplication
spec:
   ports:
    - port: 80
      targetPort: 80
   selector:
    app: topnavapplication
   type: LoadBalancer